# Generated by Django 3.2.3 on 2021-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subscription', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=10)),
            ],
        ),
    ]
